source 'https://rubygems.org'

ruby '2.1.5'

gem 'rails', '4.2.1'

gem 'rails-api'

gem 'spring', :group => :development

gem 'thin'

gem 'pg'

gem 'devise'
gem 'responders', '~> 2.0'

gem 'rack-cors', :require => 'rack/cors'


group :development, :test do
  gem 'rails-pry'
  gem 'pry'
end


# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

